name = "Parsing manual mode URLs"
type = "urlParsing"


[groups.root]
name = "Root directory"
standards = ["ERC-4804", "ERC-6860"]

[[groups.root.tests]]
name = "Without \"/\" specified"
url = "web3://0x9A595bc28F1c40ab96247E8157A2b0A6762E7543"
resolveMode = "manual"
contractCallMode = "calldata"
calldata = "0x2f"
contractReturnProcessing = "decodeABIEncodedBytes"
decodedABIEncodedBytesMimeType = "text/html"

[[groups.root.tests]]
name = "With \"/\" specified"
url = "web3://0x9A595bc28F1c40ab96247E8157A2b0A6762E7543/"
resolveMode = "manual"
contractCallMode = "calldata"
calldata = "0x2f"
contractReturnProcessing = "decodeABIEncodedBytes"
decodedABIEncodedBytesMimeType = "text/html"


[groups.paths]
name = "Paths"
standards = ["ERC-4804", "ERC-6860"]

[[groups.paths.tests]]
name = "Simple path"
url = "web3://0x9A595bc28F1c40ab96247E8157A2b0A6762E7543/view/1"
resolveMode = "manual"
contractCallMode = "calldata"
calldata = "0x2f766965772f31"
contractReturnProcessing = "decodeABIEncodedBytes"
decodedABIEncodedBytesMimeType = "text/html"

[[groups.paths.tests]]
name = "Simple path with extension setting a mimetype"
url = "web3://0x9A595bc28F1c40ab96247E8157A2b0A6762E7543/view/1.svg"
resolveMode = "manual"
contractCallMode = "calldata"
calldata = "0x2f766965772f312e737667"
contractReturnProcessing = "decodeABIEncodedBytes"
decodedABIEncodedBytesMimeType = "image/svg+xml"

[[groups.paths.tests]]
name = "Simple path with URI encoded pathname"
url = "web3://0x9A595bc28F1c40ab96247E8157A2b0A6762E7543/view/%201"
resolveMode = "manual"
contractCallMode = "calldata"
calldata = "0x2f766965772f25323031" # /view/%201
contractReturnProcessing = "decodeABIEncodedBytes"
decodedABIEncodedBytesMimeType = "text/html"

[[groups.paths.tests]]
name = "Simple path with URI encoded query"
url = "web3://0x9A595bc28F1c40ab96247E8157A2b0A6762E7543/view/1?a=1%26b%3D2"
resolveMode = "manual"
contractCallMode = "calldata"
calldata = "0x2f766965772f313f613d312532366225334432" # // /view/1?a=1%26b%3D2
contractReturnProcessing = "decodeABIEncodedBytes"
decodedABIEncodedBytesMimeType = "text/html"